server:
  port: 2022

spring:
  application:
    name: cloud-snowflake-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage
    username: root
    password: 123456