server:
  port: 9527
spring:
  application:
    name: cloud-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态路由创建动态路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route     #路由ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/findDataById #断言，路径相匹配的进行路由
            - After=2022-11-19T12:41:08.862+08:00[Asia/Shanghai] #指定时间之后
#            - Before=2022-11-19T12:41:08.862+08:00[Asia/Shanghai] #指定时间之前
#            - Between=2022-11-19T12:41:08.862+08:00[Asia/Shanghai], 2022-11-19T12:41:08.862+08:00[Asia/Shanghai] #指定时间之中
#            - Cookie=username,lvchao
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为证书的正则表达式
            - Method=Get

        - id: payment_route2  #路由ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/findDataById/lb   #断言，路径相匹配的进行路由
            - After=2022-11-19T13:41:08.862+08:00[Asia/Shanghai] #指定时间之后

eureka:
  instance:
#    hostname: cloud-getway-service
    prefer-ip-address: true
    instance-id: cloud-getway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka/
